[project]
name = "td-uvmanagedprefab"
version = "0.0.1"

description = "A prefab for TouchDesigner-Projects that will be complelty managed and run by UV."
readme = "README.md"
requires-python = "==3.11.1"
dependencies = [
    "touchlaunch",
]
keywords=["TouchDesigner"]

[tool.touchdesigner]
projectfile = "Project.toe"
enforce-version="closest-build" # Options: strict, closest-build, latest-build, latest-version

[tool.uv]
environments = [
    "sys_platform =='win32'",
    "sys_platform =='darwin'"
]

[tool.uv.sources]
touchlaunch = { git = "https://github.com/PlusPlusOneGmbH/Py_TD_Launch" }


